const usStates = [
  { name: 'Alabama', fips: '01' },
  { name: 'Alaska', fips: '02' },
  { name: 'Arizona', fips: '04' },
  { name: 'Arkansas', fips: '05' },
  { name: 'California', fips: '06' },
  { name: 'Colorado', fips: '08' },
  { name: 'Connecticut', fips: '09' },
  { name: 'Delaware', fips: '10' },
  { name: 'Florida', fips: '12' },
  { name: 'Georgia', fips: '13' },
  { name: 'Hawaii', fips: '15' },
  { name: 'Idaho', fips: '16' },
  { name: 'Illinois', fips: '17' },
  { name: 'Indiana', fips: '18' },
  { name: 'Iowa', fips: '19' },
  { name: 'Kansas', fips: '20' },
  { name: 'Kentucky', fips: '21' },
  { name: 'Louisiana', fips: '22' },
  { name: 'Maine', fips: '23' },
  { name: 'Maryland', fips: '24' },
  { name: 'Massachusetts', fips: '25' },
  { name: 'Michigan', fips: '26' },
  { name: 'Minnesota', fips: '27' },
  { name: 'Mississippi', fips: '28' },
  { name: 'Missouri', fips: '29' },
  { name: 'Montana', fips: '30' },
  { name: 'Nebraska', fips: '31' },
  { name: 'Nevada', fips: '32' },
  { name: 'New Hampshire', fips: '33' },
  { name: 'New Jersey', fips: '34' },
  { name: 'New Mexico', fips: '35' },
  { name: 'New York', fips: '36' },
  { name: 'North Carolina', fips: '37' },
  { name: 'North Dakota', fips: '38' },
  { name: 'Ohio', fips: '39' },
  { name: 'Oklahoma', fips: '40' },
  { name: 'Oregon', fips: '41' },
  { name: 'Pennsylvania', fips: '42' },
  { name: 'Rhode Island', fips: '44' },
  { name: 'South Carolina', fips: '45' },
  { name: 'South Dakota', fips: '46' },
  { name: 'Tennessee', fips: '47' },
  { name: 'Texas', fips: '48' },
  { name: 'Utah', fips: '49' },
  { name: 'Vermont', fips: '50' },
  { name: 'Virginia', fips: '51' },
  { name: 'Washington', fips: '53' },
  { name: 'West Virginia', fips: '54' },
  { name: 'Wisconsin', fips: '55' },
  { name: 'Wyoming', fips: '56' }
]

export default usStates
